logbook/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from logbook import views

urlpatterns = [
    # Other URL patterns...
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('employee-list/', views.employee_list, name='employee_list'),
    path('login/', views.login_view, name='login'),

]

source/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from logbook import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', views.main_page, name='main_page'),
    path('employee-list/', views.employee_list, name='employee_list'),
    path('accounts/', include('accounts.urls')),
    path('', views.login_view, name='login'),
    path('edit_personal_info/', views.edit_personal_info, name='edit_personal_info'),
    path('employee-management/', views.employee_management, name='employee_management'),
    path('add_employee/', views.add_employee, name='add_employee'),
    path('update-employee/<int:employee_id>/', views.update_employee, name='update_employee'),
    path('delete-employee/<int:employee_id>/', views.delete_employee, name='delete_employee'),
    path('confirm-delete-employee/<int:employee_id>/', views.confirm_delete_employee, name='confirm_delete_employee')
]

logbook/models.py
from django.db import models
from django.contrib.auth.models import User


class Department(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    mobile_phone = models.CharField(max_length=20)
    work_phone = models.CharField(max_length=20)
    email = models.EmailField()
    occupation = models.CharField(max_length=100, default='Manager')
    is_active = models.BooleanField(default=True)
    def __str__(self):
        return f"{self.first_name} {self.last_name}"

logbook/forms.py
# logbook/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Employee


from django import forms
from .models import Employee

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ('first_name', 'last_name', 'mobile_phone', 'work_phone', 'email', 'occupation', 'department')
        widgets = {
            'department': forms.Select(attrs={'required': True}),
        }


class EditPersonalInfoForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password')

logbook/views.py
from django.contrib.auth import logout, authenticate, login
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.decorators.csrf import csrf_protect
from django.core.paginator import Paginator
from .models import Employee, Department
from .forms import EmployeeForm, EditPersonalInfoForm
from django import forms


def main_page(request):
    return render(request, 'main_page.html')


def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('employee_list')
        else:
            messages.error(request, 'Invalid username or password.')
    return render(request, 'login.html')


def employee_list(request):
    departments = Department.objects.all()
    employees_per_department = 2
    paginator = Paginator(departments, employees_per_department)
    page_number = request.GET.get('page')  # Get the current page number
    page_obj = paginator.get_page(page_number)  # Get the page object for the current page

    context = {
        'page_obj': page_obj
    }
    return render(request, 'employee_list.html', context)


class EditPersonalInfoForm(forms.Form):
    email = forms.EmailField(required=False)
    password = forms.CharField(widget=forms.PasswordInput, required=False)
    confirm_password = forms.CharField(widget=forms.PasswordInput, required=False)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError("Passwords do not match.")

@login_required
def edit_personal_info(request):
    user = request.user
    try:
        employee = user.employee  # Retrieve the associated Employee instance
    except Employee.DoesNotExist:
        # Handle the case where the user doesn't have an Employee record
        # For example, redirect to a different page or display an error message
        return redirect('employee_list')

    if request.method == 'POST':
        form = EditPersonalInfoForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            if email:
                user.email = email
                user.save()

            if password:
                user.set_password(password)
                user.save()

            return redirect('employee_list')
    else:
        form = EditPersonalInfoForm(initial={'email': user.email})

    return render(request, 'edit_personal_info.html', {'form': form})

@login_required
def employee_management(request):
    if not request.user.is_staff:
        # If the user is not a staff member, redirect them to a different page
        return redirect('employee_list')

    if request.method == 'POST':
        form = EmployeeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('employee_management')
    else:
        form = EmployeeForm()

    # Retrieve the list of active employees
    employees = Employee.objects.filter(is_active=True)

    return render(request, 'employee_management.html', {'form': form, 'employees': employees})
@login_required
def add_employee(request):
    if request.method == 'POST':
        form = EmployeeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('employee_management')  # Redirect to the employee management page after adding the employee
    else:
        form = EmployeeForm()

    return render(request, 'add_employee.html', {'form': form})
@login_required
def update_employee(request, employee_id):
    employee = Employee.objects.get(id=employee_id)
    departments = Department.objects.all()  # Retrieve all departments

    if request.method == 'POST':
        form = EmployeeForm(request.POST, instance=employee)
        if form.is_valid():
            form.save()
            return redirect('employee_management')
    else:
        form = EmployeeForm(instance=employee)

    return render(request, 'update_employee.html', {'form': form, 'departments': departments})

@login_required
def confirm_delete_employee(request, employee_id):
    employee = get_object_or_404(Employee, id=employee_id)
    return render(request, 'confirm_delete_employee.html', {'employee': employee})

@login_required
def delete_employee(request, employee_id):
    employee = get_object_or_404(Employee, id=employee_id)
    if request.method == 'POST':
        employee.is_active = False
        employee.save()
    return redirect('employee_management')

templates/add_employee.html
{% extends 'base.html' %}

{% block content %}
  <h2>Add Employee</h2>
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_first_name">First Name:</label>
      {{ form.first_name }}
    </div>
    <div class="form-group">
      <label for="id_last_name">Last Name:</label>
      {{ form.last_name }}
    </div>
    <div class="form-group">
      <label for="id_mobile_phone">Mobile Phone:</label>
      {{ form.mobile_phone }}
    </div>
    <div class="form-group">
      <label for="id_work_phone">Work Phone:</label>
      {{ form.work_phone }}
    </div>
    <div class="form-group">
      <label for="id_email">Email:</label>
      {{ form.email }}
    </div>
    <div class="form-group">
      <label for="id_occupation">Occupation:</label>
      {{ form.occupation }}
    </div>
    <div class="form-group">
      <label for="id_department">Department:</label>
      {{ form.department }}
    </div>
    <button type="submit">Add</button>
  </form>
{% endblock %}

templates/base.html
<!-- base.html -->
{% load static %}

<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- Include your CSS and JavaScript files here -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">TechNet Corporation</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'employee_list' %}">Employee list</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'edit_personal_info' %}">Personal account</a>
                    </li>

                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'employee_management' %}">Employee Management</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">HR analytics</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>


                </ul>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

</body>
</html>

templates/employee_list.html
{% extends 'base.html' %}

{% block content %}
    {% for department in page_obj %}
<a class="list-group-item list-group-item-action list-group-item-dark">{{ department.name }}</a>
    <li class="list-group-item bg-o text-black"></li>
        {% if department.employee_set.all %}
            <ul>
                {% for employee in department.employee_set.all %}
                    <li>Employee name: {{ employee.first_name }} {{ employee.last_name }}</li>
                    <li>Occupation: {{ employee.occupation }}</li>
                    <li>Mobile Phone: {{ employee.mobile_phone }}</li>
                    <li>Work Phone: {{ employee.work_phone }}</li>
                    <li>Email: {{ employee.email }}</li>
                    <hr>
                {% endfor %}
            </ul>
        {% else %}
            <p>No employees found.</p>
        {% endif %}
    {% endfor %}

    <div class="text-end">
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-dark">&laquo; Previous</a>
    {% endif %}

    {% if page_obj.has_previous or page_obj.has_next %}
        <span class="mx-2">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
    {% endif %}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="btn btn-dark">Next &raquo;</a>
    {% endif %}
    </div>
{% endblock %}

templates/login.html
<!-- main_page.html -->
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <title>Document</title>
</head>
{% block content %}
    {% if user.is_authenticated %}
        <div class="position-relative py-2 px-4 text-bg-secondary border border-secondary rounded-pill">
            Welcome to the Employee Management System <svg width="30em" height="5em" viewBox="16 0 16 16" class="position-absolute top-3000 start-50 translate-middle mt-1" fill="var(--bs-secondary)" xmlns="http://www.w3.org/2000/svg"><path d="M7.247 11.14L2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z"/></svg>
        </div>
        <div class="d-flex justify-content-center">
            <h2 class="text-center" style="font-size: 20px;">You are already signed in.</h2>
        </div>
        <div class="d-flex justify-content-center align-items-center" style="height: 25vh;">
            <div class="text-center">
                <a href="{% url 'employee_list' %}" class="btn btn-secondary">Go to Employee List</a>
                <br>
                <br>
                <a href="{% url 'logout' %}" class="btn btn-secondary">Logout</a>
            </div>
        </div>
    {% else %}
        <div class="position-relative py-2 px-4 text-bg-secondary border border-secondary rounded-pill">
            Welcome to the Employee Management System <svg width="30em" height="5em" viewBox="16 0 16 16" class="position-absolute top-3000 start-50 translate-middle mt-1" fill="var(--bs-secondary)" xmlns="http://www.w3.org/2000/svg"><path d="M7.247 11.14L2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z"/></svg>
        </div>
        <div class="d-flex justify-content-center">
            <h2 class="text-center" style="font-size: 20px;">Please sign in to the system</h2>
        </div>
        <div class="d-flex justify-content-center align-items-center" style="height: 25vh;">
            {% csrf_token %}
            <form method="post" action="{% url 'login' %}" style="width: 300px;">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" id="username" name="username" class="form-control" required>
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" id="password" name="password" class="form-control" required>
                </div>
                <div class="d-flex justify-content-center mt-3">
                    <button type="submit" class="btn btn-secondary w-50">Sign in</button>
                </div>
            </form>
        </div>
    {% endif %}
{% endblock %}

templates/main_page.html
<!-- main_page.html -->
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <title>Document</title>
</head>
{% block content %}
    {% if user.is_authenticated %}
        <div class="position-relative py-2 px-4 text-bg-secondary border border-secondary rounded-pill">
            Welcome to the Employee Management System <svg width="30em" height="5em" viewBox="16 0 16 16" class="position-absolute top-3000 start-50 translate-middle mt-1" fill="var(--bs-secondary)" xmlns="http://www.w3.org/2000/svg"><path d="M7.247 11.14L2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z"/></svg>
        </div>
        <div class="d-flex justify-content-center">
            <h2 class="text-center" style="font-size: 20px;">You are already signed in.</h2>
        </div>
        <div class="d-flex justify-content-center align-items-center" style="height: 25vh;">
            <div class="text-center">
                <a href="{% url 'employee_list' %}" class="btn btn-secondary">Go to Employee List</a>
                <br>
                <br>
                <a href="{% url 'logout' %}" class="btn btn-secondary">Logout</a>
            </div>
        </div>
    {% else %}
        <div class="position-relative py-2 px-4 text-bg-secondary border border-secondary rounded-pill">
            Welcome to the Employee Management System <svg width="30em" height="5em" viewBox="16 0 16 16" class="position-absolute top-3000 start-50 translate-middle mt-1" fill="var(--bs-secondary)" xmlns="http://www.w3.org/2000/svg"><path d="M7.247 11.14L2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z"/></svg>
        </div>
        <div class="d-flex justify-content-center">
            <h2 class="text-center" style="font-size: 20px;">Please sign in to the system</h2>
        </div>
        <div class="d-flex justify-content-center align-items-center" style="height: 25vh;">
            {% csrf_token %}
            <form method="post" action="{% url 'login' %}" style="width: 300px;">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" id="username" name="username" class="form-control" required>
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" id="password" name="password" class="form-control" required>
                </div>
                <div class="d-flex justify-content-center mt-3">
                    <button type="submit" class="btn btn-secondary w-50">Sign in</button>
                </div>
            </form>
        </div>
    {% endif %}
{% endblock %}

templates/update_employee.html
{% extends 'base.html' %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    <div class="input-group input-group-sm mb-3">
      <span class="input-group-text" id="inputGroup-sizing-sm">Department:</span>
      {{ form.department }}
    </div>
    <div class="input-group input-group-sm mb-3">
      <span class="input-group-text" id="inputGroup-sizing-sm">First Name:</span>
      <input type="text" class="form-control" id="id_first_name" name="first_name" placeholder="Enter first name" value="{{ form.first_name.value }}">
    </div>
    <div class="input-group input-group-sm mb-3">
      <span class="input-group-text" id="inputGroup-sizing-sm">Last Name:</span>
      <input type="text" class="form-control" id="id_last_name" name="last_name" placeholder="Enter last name" value="{{ form.last_name.value }}">
    </div>
    <div class="input-group input-group-sm mb-3">
      <span class="input-group-text" id="inputGroup-sizing-sm">Mobile Phone:</span>
      <input type="text" class="form-control" id="id_mobile_phone" name="mobile_phone" placeholder="Enter mobile phone" value="{{ form.mobile_phone.value }}">
    </div>
    <div class="input-group input-group-sm mb-3">
      <span class="input-group-text" id="inputGroup-sizing-sm">Work Phone:</span>
      <input type="text" class="form-control" id="id_work_phone" name="work_phone" placeholder="Enter work phone" value="{{ form.work_phone.value }}">
    </div>
    <div class="input-group input-group-sm mb-3">
      <span class="input-group-text" id="inputGroup-sizing-sm">Email:</span>
      <input type="email" class="form-control" id="id_email" name="email" placeholder="Enter email" value="{{ form.email.value }}">
    </div>
    <div class="input-group input-group-sm mb-3">
      <span class="input-group-text" id="inputGroup-sizing-sm">Occupation:</span>
      <input type="text" class="form-control" id="id_occupation" name="occupation" placeholder="Enter occupation" value="{{ form.occupation.value }}">
    </div>

    <div class="d-flex justify-content-center mt-3">
      <button type="submit" class="btn btn-secondary w-25">Update</button>
    </div>
  </form>
{% endblock %}